In [1]:
import sys
sys.path.append("../src")

from OmiScraper import OmiScraper
from RealListing import RealListing

import pandas as pd
from io import StringIO

## 1. Creation of the dataset for the area of the apartment from the OMI website
Since the apartment to sell is of course localized in a single area of the OMI dataset, this step will be quick and only contains the details about the specific area.

This process will be carried on by using the class ***OmiScraper*** created for this specific purpose

Each area-level dataset follows a standardized structure, combining the original OMI table with additional contextual features:

Original OMI data (from HTML table):
- Province -> Rome
- Area -> Name of the area (e.g. San Paolo)
- Tipologia
- Stato conservativo
- Valori Compravendita (Min / Max)
- Valori Locazione (Min / Max)
- Superficie

Additional engineered features (from OMI dataset):
From the OMI website:
- area_name
- html_table
- zona
- codice_zona
- microzona_catastale
- tipologia_prevalente

**Note**: A similar structure and class will be used for the Rome dataset

In [4]:
dt = OmiScraper()

In [6]:
html_code = """<table class="table table-striped table-hover table-header table-bordered" summary="La tabella riporta i valori delle quotazioni del mercato immobiliare per il semestre selezionato">
<thead><tr><th rowspan="2">Tipologia</th><th rowspan="2">Stato conservativo</th><th id="vm" colspan="2">Valori Compravendita (€/mq)</th><th rowspan="2">Superficie (L/N)</th><th id="vl" colspan="2">Valori Locazione (€/mq x mese)</th><th rowspan="2">Superficie (L/N)</th></tr><tr><th id="vmmin">Min</th><th id="vmmax">Max</th><th id="vlmin">Min</th><th id="vlmax">Max</th></tr></thead><tbody><tr><td class="sin">Abitazioni civili</td><td class="sin">NORMALE</td><td class="dx" headers="vm vmmin">1850</td><td class="dx" headers="vm vmmax">2750</td><td class="center">L</td><td class="dx" headers="vl vlmax">8</td><td class="dx" headers="vl vlmax">12</td><td class="center">L</td></tr></tbody><tbody><tr><td class="sin">Abitazioni di tipo economico</td><td class="sin">NORMALE</td><td class="dx" headers="vm vmmin">1750</td><td class="dx" headers="vm vmmax">2600</td><td class="center">L</td><td class="dx" headers="vl vlmax">7</td><td class="dx" headers="vl vlmax">10</td><td class="center">L</td></tr></tbody><tbody><tr><td class="sin">Box</td><td class="sin">NORMALE</td><td class="dx" headers="vm vmmin">1100</td><td class="dx" headers="vm vmmax">1650</td><td class="center">L</td><td class="dx" headers="vl vlmax">4</td><td class="dx" headers="vl vlmax">6</td><td class="center">L</td></tr></tbody><tbody><tr><td class="sin">Ville e Villini</td><td class="sin">NORMALE</td><td class="dx" headers="vm vmmin">2100</td><td class="dx" headers="vm vmmax">3000</td><td class="center">L</td><td class="dx" headers="vl vlmax">8</td><td class="dx" headers="vl vlmax">11,5</td><td class="center">L</td></tr></tbody></table>"""

In [8]:
dt.add_dt_col("Isola Sacra",
             html_code, 
             "Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO)", 
             "D1", 
             0, 
             "Abitazioni Civili")

,Tipologia,Stato conservativo,Valori Compravendita (€/mq) - Min,Valori Compravendita (€/mq) - Max,Superficie (L/N),Valori Locazione (€/mq x mese) - Min,Valori Locazione (€/mq x mese) - Max,Superficie (L/N) - Superficie (L/N).1,Area,Province,Municipality,Fascia/Zona,Codice Zona,Microzona Catastale,Tipologia prevalente,Destinazione
0,Abitazioni civili,NORMALE,1850,2750,L,8,12,L,Isola Sacra,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili,Residenziale
1,Abitazioni di tipo economico,NORMALE,1750,2600,L,7,10,L,Isola Sacra,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili,Residenziale
2,Box,NORMALE,1100,1650,L,4,6,L,Isola Sacra,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili,Residenziale
3,Ville e Villini,NORMALE,2100,3000,L,8,115,L,Isola Sacra,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili,Residenziale

In [10]:
dt_fiumicino = dt.current_dt()
dt_fiumicino

,Tipologia,Stato conservativo,Valori Compravendita (€/mq) - Min,Valori Compravendita (€/mq) - Max,Superficie (L/N),Valori Locazione (€/mq x mese) - Min,Valori Locazione (€/mq x mese) - Max,Superficie (L/N) - Superficie (L/N).1,Area,Province,Municipality,Fascia/Zona,Codice Zona,Microzona Catastale,Tipologia prevalente,Destinazione
0,Abitazioni civili,NORMALE,1850,2750,L,8,12,L,Isola Sacra,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili,Residenziale
1,Abitazioni di tipo economico,NORMALE,1750,2600,L,7,10,L,Isola Sacra,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili,Residenziale
2,Box,NORMALE,1100,1650,L,4,6,L,Isola Sacra,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili,Residenziale
3,Ville e Villini,NORMALE,2100,3000,L,8,115,L,Isola Sacra,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili,Residenziale

In [12]:
dt_fiumicino.to_csv("OMI_FCO.csv", index = False)

## 2. Creation of the real listing dataset from real estate websites
The creation of this dataset required manual collection of information from real estate listing websites.

To make the process more structured and partially automated, a custom class, ***RealListing***, was created. The class allows each listing to be inserted using a consistent set of fields, reducing manual repetition and helping keep the dataset organized.

The inserted features are:
- Street = address name
- Price = integer
- Surface = integer
- N. of Rooms = integer
- N. of Bathrooms = integer
- External Area = B/T/G/N (Balcony, Terrace, Garden, None)
- External Surface = integer
- Floor = integer
- Levels = integer
- Parking = O/C/B/N (Outdoor, Covered, Box, None)
- Furnished = Y/N/P (Yes, No, Partially)
- Conditions = 1: New, 2: Good Condition, 3: Full Renovation Needed
- Construction Year = integer
- Property = available / bare ownership

To ensure consistency across the dataset, predefined formats and categories were used when inserting the data (e.g. categorical values encoded with fixed labels). This reduces variability due to manual input and makes the dataset more suitable for analysis.

In [16]:
fiumicino = RealListing("Isola Sacra (FCO) - Via Trincea delle Frasche")

In [528]:
fiumicino.characteristics(street = "Via Condino", price = 250, mq = 55, rooms = 3, bathrooms = 1, 
                        exteriors = "T", ex_surface = 0,  floor = 3, levels = 3, parking = "O",
                        furnished = "N", conditions = 1, construction_year = 2026, proprieta = "new construction")

Careful, this street name has already been added

Do you still want to insert the record?: Y or N y

,Area,Street,ID_Number,Price,Surface,N. of Rooms,N. of Bathrooms,External Area,External Surface,Floor,Levels,Parking Space,Furnished,Conditions,Property,Construction Year,ID_number,Stree
0,Isola Sacra (FCO) - Via Trincea delle Frasche,Passo Buole,Iso_Buo_1,296000,130,4,3,B,40,3,3,O,N,2,available,2019.0,NaN,NaN
1,Isola Sacra (FCO) - Via Trincea delle Frasche,Trince delle Frasche,Iso_Fra_2,197000,60,2,1,T,0,1,2,O,N,1,available,2025.0,NaN,NaN
2,Isola Sacra (FCO) - Via Trincea delle Frasche,Trince delle Frasche,Iso_Fra_3,285000,125,4,3,B,0,1,2,B,N,1,available,2026.0,NaN,NaN
3,Isola Sacra (FCO) - Via Trincea delle Frasche,Trince delle Frasche,Iso_Fra_4,235000,98,4,3,G,0,1,2,B,N,2,Auction,2026.0,NaN,NaN
4,Isola Sacra (FCO) - Via Trincea delle Frasche,Bruno Carloni,Iso_Car_5,205000,68,3,1,T,NaN,2,2,B,Y,2,available,2026.0,NaN,NaN
5,Isola Sacra (FCO) - Via Trincea delle Frasche,Athos Maestri,Iso_Mae_6,235000,126,3,1,B + T,NaN,1,1,O,Y,3,available,1983.0,NaN,NaN
6,Isola Sacra (FCO) - Via Trincea delle Frasche,Angelo Siffredi,Iso_Sif_7,390000,120,5,1,T + B + G,100,1,1,O,N,1,new consruction,2026.0,NaN,NaN
7,Isola Sacra (FCO) - Via Trincea delle Frasche,A. Zezon,Iso_Zez_8,390000,105,4,2,T + B + G,NaN,1,2,O,N,2,new consruction,2026.0,NaN,NaN
8,Isola Sacra (FCO) - Via Trincea delle Frasche,Gaetano Carolei,Iso_Car_9,450000,170,6,2,T + B + G,300,whole building,2,B,N,1,new consruction,2026.0,NaN,NaN
9,Isola Sacra (FCO) - Via Trincea delle Frasche,Gherardo Vaiarini,Iso_Vai_10,459000,400,6,4,T + B + G,300,whole building,3,B + C,N,2,available,1980.0,NaN,NaN
10,Isola Sacra (FCO) - Via Trincea delle Frasche,A. Zezon,Iso_Zez_11,139000,48,2,1,B + G,125,0,3,B,N,2,new construction,2026.0,NaN,NaN
11,Isola Sacra (FCO) - Via Trincea delle Frasche,A. Zezon,Iso_Zez_12,139000,48,2,1,B + G,50,0,3,B,N,2,new construction,2026.0,NaN,NaN
12,Isola Sacra (FCO) - Via Trincea delle Frasche,Teresio Martinoli,Iso_Mar_13,249000,75,2,2,B + G,25,whole building,2,O,N,2,available,1990.0,Iso_Mar_13,NaN
13,Isola Sacra (FCO) - Via Trincea delle Frasche,A. Zezon,Iso_Zez_14,249000,100,3,2,B + G,130,1,1,O,N,2,available,1980.0,NaN,NaN
14,Isola Sacra (FCO) - Via Trincea delle Frasche,Passo Buole,Iso_Buo_15,123000,43,3,2,T,NaN,2,2,O,N,2,auction,1980.0,NaN,NaN
15,Isola Sacra (FCO) - Via Trincea delle Frasche,Passo Buole,Iso_Buo_16,290000,142,3,2,T,NaN,2,2,O,N,2,available,1984.0,NaN,NaN
16,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_17,259000,136,3,1,B,NaN,1,3,N,N,1,available,1990.0,NaN,NaN
17,Isola Sacra (FCO) - Via Trincea delle Frasche,Alberto Brondi,Iso_Bro_18,275000,200,8,2,B + T + G,450,whole building,2,N,N,2,missing documentation,NaN,NaN,NaN
18,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_19,259000,123,3,2,B,NaN,2,2,N,N,2,available,1965.0,NaN,NaN
19,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_20,285000,120,4,2,G,NaN,1,1,B,N,2,available,1984.0,NaN,NaN
20,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_21,285000,120,6,1,G,NaN,2,2,B,N,2,available,1984.0,NaN,NaN
21,Isola Sacra (FCO) - Via Trincea delle Frasche,Via Debeli,Iso_Deb_22,259000,70,4,2,G,NaN,1,1,O,N,2,available,1980.0,NaN,NaN
22,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_23,594000,240,10,2,T + B,NaN,whole Building,2,B,N,2,available,1984.0,NaN,NaN
23,Isola Sacra (FCO) - Via Trincea delle Frasche,Passo Buole,Iso_Buo_24,239000,99,4,2,N,NaN,1,2,B,P,2,available,NaN,NaN,NaN
24,Isola Sacra (FCO) - Via Trincea delle Frasche,Passo Buole,Iso_Buo_25,123000,77,4,1,T + B,NaN,2,3,NaN,P,2,auction,NaN,NaN,NaN
25,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_26,235000,98,5,1,B,NaN,0,3,NaN,N,2,auction,NaN,NaN,NaN
26,Isola Sacra (FCO) - Via Trincea delle Frasche,Antonio Cambriglia,Iso_Cam_27,235000,110,5,1,B + T,NaN,NaN,NaN,NaN,N,1,new construction,2026.0,NaN,NaN
27,Isola Sacra (FCO) - Via Trincea delle Frasche,Ferdinando Guerci,Iso_Gue_28,195000,71,2,1,B,NaN,1,2,N,N,2,available,NaN,NaN,NaN
28,Isola Sacra (FCO) - Via Trincea delle Frasche,Foscolo Montini,Iso_Mon_29,335000,100,4,2,B + G,150,whole Building,2,O,N,1,new construction,2026.0,NaN,NaN
29,Isola Sacra (FCO) - Via Trincea delle Frasche,Foscolo Montini,Iso_Mon_30,209000,120,4,2,B + T + G,NaN,0,1,B,N,1,new construction,2026.0,NaN,NaN
30,Isola Sacra (FCO) - Via Trincea delle Frasche,Stellato Spalletti,Iso_Spa_31,365000,115,4,2,B + G,NaN,whole building,2,O,N,1,new construction,2026.0,NaN,NaN
31,Isola Sacra (FCO) - Via Trincea delle Frasche,Stellato Spalletti,Iso_Spa_32,390000,117,5,2,B + G,NaN,whole building,2,O,N,1,new construction,2026.0,NaN,NaN
32,Isola Sacra (FCO) - Via Trincea delle Frasche,Sei Busi,Iso_Bus_33,249000,84,3,1,B,NaN,2,4,N,N,1,new construction,2026.0,NaN,NaN
33,Isola Sacra (FCO) - Via Trincea delle Frasche,Col Fenilon,Iso_Fen_34,349000,145,5,2,B + G,450,whole building,2,B,N,2,available,1990.0,NaN,NaN
34,Isola Sacra (FCO) - Via Trincea delle Frasche,Vittorio Marandola,Iso_Mar_35,279000,128,5,2,B + G,80,whole building,2,O,N,2,available,2014.0,NaN,Vittorio Marandola
35,Isola Sacra (FCO) - Via Trincea delle Frasche,Angelo Siffredi,Iso_Sif_36,339000,120,4,2,T,240,3,3,O,N,1,available,2014.0,NaN,NaN
36,Isola Sacra (FCO) - Via Trincea delle Frasche,Via Condino,Iso_Con_37,220000,55,3,1,T,0,2,3,O,N,1,new construction,2026.0,NaN,NaN
37,Isola Sacra (FCO) - Via Trincea delle Frasche,Via Condino,Iso_Con_38,174000,42,2,1,T,0,1,3,O,N,1,new construction,2026.0,NaN,NaN
38,Isola Sacra (FCO) - Via Trincea delle Frasche,Via Condino,Iso_Con_39,175000,43,2,1,T,0,2,3,O,N,1,new construction,2026.0,NaN,NaN
39,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_40,225000,94,4,1,G,354,1,1,O,N,1,new construction,2026.0,NaN,NaN
40,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_41,200000,90,4,1,G,228,1,1,O,N,1,new construction,2026.0,NaN,NaN
41,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_42,175000,70,3,1,G,239,1,1,O,N,1,new construction,2026.0,NaN,NaN
42,Isola Sacra (FCO) - Via Trincea delle Frasche,Via Condino,Iso_Con_43,250000,55,3,1,T,0,3,3,O,N,1,new construction,2026.0,NaN,NaN

## 3. Converting the object to a dataset
At this stage, the data is still stored within the custom class object. In order to perform further analysis, it needs to be converted into a pandas DataFrame.
This is done by applying the ***.dataset()*** method to the object, which returns the structured dataset in tabular form.

A quick check using ***.head()*** is then performed to verify that the conversion was successful and that the dataset has the expected structure.

In [530]:
dt_fco = fiumicino.dataset()
dt_fco.head(5)

,Area,Street,ID_Number,Price,Surface,N. of Rooms,N. of Bathrooms,External Area,External Surface,Floor,Levels,Parking Space,Furnished,Conditions,Property,Construction Year,ID_number,Stree
0,Isola Sacra (FCO) - Via Trincea delle Frasche,Passo Buole,Iso_Buo_1,296000,130,4,3,B,40,3,3,O,N,2,available,2019.0,NaN,NaN
1,Isola Sacra (FCO) - Via Trincea delle Frasche,Trince delle Frasche,Iso_Fra_2,197000,60,2,1,T,0,1,2,O,N,1,available,2025.0,NaN,NaN
2,Isola Sacra (FCO) - Via Trincea delle Frasche,Trince delle Frasche,Iso_Fra_3,285000,125,4,3,B,0,1,2,B,N,1,available,2026.0,NaN,NaN
3,Isola Sacra (FCO) - Via Trincea delle Frasche,Trince delle Frasche,Iso_Fra_4,235000,98,4,3,G,0,1,2,B,N,2,Auction,2026.0,NaN,NaN
4,Isola Sacra (FCO) - Via Trincea delle Frasche,Bruno Carloni,Iso_Car_5,205000,68,3,1,T,NaN,2,2,B,Y,2,available,2026.0,NaN,NaN

## 4. Export to CSV

In [ ]:
dt_fco.to_csv("Real_Listing_dt_Fiumicino.csv", index = False)

---
****This dataset serves as the foundation for the subsequent real estate analysis.****