In [1]:
import sys
sys.path.append("../src")

from OmiScraper import OmiScraper
from AreasDictionaries import university_areas
from AreasDictionaries import area_university_list
from Functions import area_uni_finder, area_check

import pandas as pd

In [107]:
class RealListing:
    def __init__(self, area):
        self.area = area
        self.df = pd.DataFrame(columns = ["Area", "Street", "ID_Number", "Surface", "N. of Rooms", "N. of Bathrooms", "External Area", 
                                          "Price", "Floor", "Furnished", "Conditions", "Property"])
        

    
    def characteristics(self, street, mq, rooms, bathrooms, exteriors, price, floor, furnished, conditions, proprieta):
        # street_id = street.split()[1]
        # try:
        #     street_id = street.split()[1]
        # except IndexError:
        #     street_id = street.split()[0]

        street_id = street.split()[-1]
        area_id = self.area.split()[-1]
        
        flat_id = area_id[0:3] + "_" + street_id[0:3] + "_" + str(len(self.df)+1)

        if (self.df["Street"] == street).any():
            while True:
                print("Careful, this street name has already been added")
                keep_on = input("Do you still want to insert the record?: Y or N").lower()
    
                if keep_on == "y":
                    break
    
                elif keep_on == "n":
                    return
            
        if (self.df["ID_Number"] == flat_id).any():
            print("The apartment at this id has been already inserted!")
            return

        else:
            column = {"Area": self.area, "Street": street, "ID_Number": flat_id, 
                      "Surface":mq, "N. of Rooms": rooms, "N. of Bathrooms": bathrooms, "External Area": exteriors,
                      "Price": price * 1000, "Floor": floor, "Furnished": furnished, "Conditions": conditions, "Property": proprieta}
            df2 = pd.DataFrame([column])
            self.df = pd.concat([self.df, df2], axis = 0, ignore_index = True)
            return self.df

    def dataset(self):
        return self.df

    def delete_last_row(self):
        self.df = self.df.drop(self.df.index[-1])

    def delete_row(self, row_index):
        self.df = self.df.drop(row_index)
        

    def characteristics1(self):
        rows = []
        for i in range(11):
            print(f"Insert the characteristics of the apartment for apartment {i}: \n")
            area = input(f"Insert area for aparment {i}: \n")
            street = input(f"Insert street for aparment {i}: \n")
            mq = int(input(f"Insert surface for aparment {i}: \n"))
            rooms = int(input(f"Insert number of rooms for aparment {i}:\n"))
            price = int(input(f"Insert prices for aparment {i}: \n"))
            floor = int(input(f"Insert floor for aparment {i}: \n"))
            furnished = input(f"Insert furnished for aparment {i}: \n")
            row = {"Area": area, "Street": street, "Surface":mq, 
                                              "N. of Rooms": rooms, "Price": price,
                                              "Floor": floor, "Furnished": furnished}
            rows.append(row)            
        self.df = pd.DataFrame(rows)
        return self.df

#### Dataframe - Area
- Street = "address_name"
- Surface = int 
- N. of Rooms = int
- N. of Bathrooms = int
- External Area = B/T/G/N (Balcony, Terrace, Garden, No)
- Price = int 
- Floor = int 
- Furnished = Y/N/P (Yes, No, Partially) 
- Conditions = {1: "New", 2: "Good Condition", 3: "Full Rennovation"}
- Property = nuda/available
  
(Street, Surface, N. of Rooms, N. of Bathrooms, External Area, Price, Floor, Furnished, Conditions)

In [6]:
flaminio = RealListing("Flaminio")

In [48]:
flaminio.characteristics(street = "Giovanni Paolo Pannini", mq = 88, rooms = 5, bathrooms = 2, 
                        exteriors = "B", price = 595, floor = 3, furnished = "N", conditions = 2, proprieta = "available")

Careful, this street name has already been added

Do you still want to insert the record?: Y or N y

,Area,Street,ID_Number,Surface,N. of Rooms,N. of Bathrooms,External Area,Price,Floor,Furnished,Conditions,Property
0,Flaminio,Viale Pinturicchio,Fla_Pin_1,95,5,2,N,355000,1,Y,2,nuda
1,Flaminio,Giovanni Paolo Pannini,Fla_Pan_2,85,2,1,T,490000,2,P,1,available
2,Flaminio,Giuseppe Sacconi,Fla_Sac_3,65,5,1,N,460000,3,N,2,available
3,Flaminio,Cesare Fracassini,Fla_Fra_4,67,2,1,B,440000,5,N,2,available
4,Flaminio,Antonio Mancini,Fla_Man_5,70,3,1,N,439,1,P,2,available
5,Flaminio,Flaminia,Fla_Fla_6,82,2,1,B,540000,3,P,2,available
6,Flaminio,Viale del Vignola,Fla_Vig_7,85,3,1,B,399000,1,N,1,available
7,Flaminio,Viale Pinturicchio,Fla_Pin_8,85,2,1,B,470000,2,N,2,available
8,Flaminio,Giulio Tomano,Fla_Tom_9,120,3,2,B,640000,3,P,2,available
9,Flaminio,Giovanni Paolo Pannini,Fla_Pan_10,88,5,2,B,595000,3,N,2,available

In [ ]:
dt_fla.loc[4,"Price"] = 439

In [54]:
dt_fla.to_csv("Real_listing_dt_flaminio.csv", index=False)

---
---

In [58]:
trieste = RealListing("Trieste")

In [80]:
trieste.characteristics(street = "Appennino", mq = 50, rooms = 3, bathrooms = 1, 
                        exteriors = "T", price = 615, floor = 2, furnished = "N", conditions = 2, proprieta = "available")

,Area,Street,ID_Number,Surface,N. of Rooms,N. of Bathrooms,External Area,Price,Floor,Furnished,Conditions,Property
0,Trieste,Corso Trieste,Tri_Tri_1,60,2,1,T,535000,1,N,2,available
1,Trieste,Palazzo Ada,Tri_Ada_2,69,2,1,T,624000,1,N,1,available
2,Trieste,Palazzo Ada,Tri_Ada_3,71,2,1,T,666000,1,N,1,available
3,Trieste,Corso Trieste,Tri_Tri_4,101,2,1,T,580000,1,N,1,available
4,Trieste,Spalato,Tri_Spa_5,111,3,1,T,680000,5,N,1,available
5,Trieste,Ticino,Tri_Tic_6,50,2,1,B,490000,1,N,1,available
6,Trieste,Ticino,Tri_Tic_7,55,2,1,B,490000,1,N,1,available
7,Trieste,Piazza Buenos Aires,Tri_Air_8,55,4,1,B,615000,2,N,2,available
8,Trieste,Tolimino,Tri_Tol_9,63,3,1,T,615000,1,N,2,available
9,Trieste,Appennino,Tri_App_10,50,3,1,T,615000,2,N,2,available

In [ ]:
dt_tri.loc[3, "Price"] = 580000

In [84]:
dt_tri.to_csv("Real_listing_dt_trieste.csv", index=False)

---
---

In [ ]:
parioli = RealListing("Parioli")

In [49]:
parioli.characteristics(street = "Viale Romania", mq = 106, rooms = 4, bathrooms = 2, 
                        exteriors = "N", price = 650, floor = 1, furnished = "P", conditions = 2)

,Area,Street,ID_Number,Surface,N. of Rooms,N. of Bathrooms,External Area,Price,Floor,Furnished,Conditions
0,Parioli,Largo Fregoli,Par_Fre_1,78,2,2,T,499000,0,N,1
1,Parioli,Largo Elvezia,Par_Elv_2,72,3,1,T,560000,0,Y,2
2,Parioli,Gaetano donnizetti,Par_don_3,72,2,2,B,610000,4,N,2
3,Parioli,Giuseppe Mangilio,Par_Man_4,94,3,1,B,399000,-1,N,3
4,Parioli,Villa Emiliani,Par_Emi_5,50,2,1,N,479000,3,N,1
5,Parioli,Belle Arti,Par_Art_6,96,3,2,B,680000,3,Y,2
6,Parioli,Gualtiero Castellini,Par_Cas_7,53,2,1,B,398000,2,N,2
7,Parioli,Ettore Ximenes,Par_Xim_8,91,3,2,N,500000,T,P,2
8,Parioli,Villa San Filippo,Par_San_9,81,2,2,N,490000,-1,N,2
9,Parioli,Viale Romania,Par_Rom_10,106,4,2,N,650000,1,P,2

In [56]:
dt_par.to_csv("Real_listing_dt_parioli.csv", index=False)

NameError: name 'dt_par' is not defined

In [157]:
dt_par = pd.read_csv("Real_listing_dt_parioli.csv")
dt_par["Price"].mean()

526500.0

---
---

In [115]:
san_lorenzo = RealListing("San Lorenzo")

In [145]:
san_lorenzo.characteristics(street = "Scalo San Lorenzo", mq = 63, rooms = 2, bathrooms = 1, 
                        exteriors = "B", price = 379, floor = 4, furnished = "P", conditions = 1, proprieta = "available")

,Area,Street,ID_Number,Surface,N. of Rooms,N. of Bathrooms,External Area,Price,Floor,Furnished,Conditions,Property
0,San Lorenzo,Via dei Sabelli,Lor_Sab_1,72,2,1,T,380000,1,N,1,available
1,San Lorenzo,Via dei Sabelli,Lor_Sab_2,50,2,1,B,300000,1,Y,2,available
2,San Lorenzo,Via dei Dalmati,Lor_Dal_3,100,3,1,B,460000,2,Y,2,available
3,San Lorenzo,Via dei Sardi,Lor_Sar_4,72,3,1,B,360000,1,N,1,available
4,San Lorenzo,Via dei Sabelli,Lor_Sab_5,120,4,2,T,480000,1,N,3,available
5,San Lorenzo,Porta Labicana,Lor_Lab_6,108,4,2,B,425000,3,Y,2,available
6,San Lorenzo,Via degli Anamari,Lor_Ana_7,60,2,1,T,359000,4,Y,1,available
7,San Lorenzo,Via dei Sabelli,Lor_Sab_8,72,2,2,B,380000,0,N,1,available
8,San Lorenzo,Via dei Volsci,Lor_Vol_9,57,2,1,B,365000,1,Y,2,available
9,San Lorenzo,Scalo San Lorenzo,Lor_Lor_10,63,2,1,B,379000,4,P,1,available

In [125]:
dt_slor = san_lorenzo.dataset()
dt_slor.loc[0, "Conditions"] = 1

In [147]:
dt_slor.to_csv("Real_listing_dt_SLor.csv", index=False)